### ISSUE TITLE
No space left on device.

### ISSUE THREAD

**Issue by dmlb2000** [varasys/corezfs#7]
I've tried several different configurations of a VM running CoreOS and can't seem to get the script to run to completion I get a lot of no space left on device consistently curing the linking of zfs kernel modules...

Latest stable version of CoreOS 1688.5.3

**Comment by kcwitt** [comment]
Yeah, there wasn't enough free space in the CoreOS development image anymore. I update the script to bind mount a tmp directory into the container, so v2.0.6 should build. I also uploaded the build artifacts to the release page at https://github.com/varasys/corezfs/files/2005034/corezfs_amd64-usr_1688.5.3_stable.tar.gz. Note that this is tied to kernel version 4.14.32-coreos (not CoreOS version 1688.5.3), so will work for all future CoreOS releases that use the 4.14.32 kernel.

Note that this script should be a stopgap measure, as I am not actively maintaining it anymore (got sick of chasing CoreOS on every update). I have found ArchLinux to be a great alternative to CoreOS (except for the initial hassle of getting it on a VPS). We are currently working on https://github.com/varasys/paczfs, which is basically ArchLinux on a ZFS root filesystem (the docs on github may not be current though).

Happy to donate the script to anyone else who finds it useful and wants to maintain it.
